apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name:  e2e-task
spec:
  inputs:
    resources:
      - name: source-repo
        type: git

  steps:
    - name: e2e-test
      image: golang:alpine
      workingDir: /workspace/source-repo/e2e
      command:
        - /bin/sh
      args:
        - /workspace/source-repo/e2e/start-test-alpine.sh
      securityContext:
        privileged: true
