apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: wiki-pipelinerun-
spec:
  serviceAccount: kbaig
  pipelineRef:
    name: cicd-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: wiki-src
